-- ============================================================================
-- 收入記帳模組表結構定義
-- 主表：INC_INCOME_MAIN （當前資料）
-- 歷史表：INC_INCOME_HIST （所有歷史紀錄）
-- ============================================================================

-- ============================================================================
-- 1. INC_INCOME_MAIN - 收入記帳主表（當前資料）
-- ============================================================================
CREATE TABLE "ADMIN"."INC_INCOME_MAIN" 
(
	"SID" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE,
	"INCOME_ID" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE,
	"BILL_DATE" DATE NOT NULL ENABLE,
	"INVOICE_NO" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"CUSTOMER_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE,
	"PROJECT" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"PERSONNEL" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	"LOCATION" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"QUOTE_AMOUNT" NUMBER NOT NULL ENABLE,
	"ACTUAL_AMOUNT" NUMBER NOT NULL ENABLE,
	"UNCOLLECTED_AMOUNT" NUMBER NOT NULL ENABLE,
	"COLLECTION_METHOD" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	"COLLECTION_STATUS" CHAR(1) COLLATE "USING_NLS_COMP" DEFAULT 'N' NOT NULL ENABLE,
	"COST_AMOUNT" NUMBER,
	"ESTIMATED_PROFIT" NUMBER,
	"REMARK" VARCHAR2(500) COLLATE "USING_NLS_COMP",
	"CREATE_USER" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	"CREATE_TIME" DATE DEFAULT NULL,
	"MOTIFER" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	"MOTIFY_TIME" DATE,
	CONSTRAINT "PK_INC_INCOME_MAIN" PRIMARY KEY ("SID")
	USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DATA" ENABLE,
	CONSTRAINT "UQ_INC_INCOME_ID" UNIQUE ("INCOME_ID")
	USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DATA" ENABLE,
	CONSTRAINT "CK_INC_COLLECTION_STATUS" CHECK (COLLECTION_STATUS IN ('Y', 'N')) ENABLE
)  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA";

-- ============================================================================
-- 2. INC_INCOME_HIST - 收入記帳歷史表（所有歷史紀錄）
-- ============================================================================
CREATE TABLE "ADMIN"."INC_INCOME_HIST" 
(
	"SID" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE,
	"INCOME_ID" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE,
	"BILL_DATE" DATE,
	"INVOICE_NO" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"CUSTOMER_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"PROJECT" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"PERSONNEL" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	"LOCATION" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"QUOTE_AMOUNT" NUMBER,
	"ACTUAL_AMOUNT" NUMBER,
	"UNCOLLECTED_AMOUNT" NUMBER,
	"COLLECTION_METHOD" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	"COLLECTION_STATUS" CHAR(1) COLLATE "USING_NLS_COMP",
	"COST_AMOUNT" NUMBER,
	"ESTIMATED_PROFIT" NUMBER,
	"REMARK" VARCHAR2(500) COLLATE "USING_NLS_COMP",
	"MOTIFER" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	"MOTIFY_TIME" DATE,
	CONSTRAINT "PK_INC_INCOME_HIST" PRIMARY KEY ("SID")
	USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DATA" ENABLE
)  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA";

-- ============================================================================
-- 3. 建立索引，優化查詢效能
-- ============================================================================
CREATE INDEX "IDX_INC_INCOME_MAIN_BILL_DATE" ON "ADMIN"."INC_INCOME_MAIN"("BILL_DATE");
CREATE INDEX "IDX_INC_INCOME_MAIN_CUSTOMER" ON "ADMIN"."INC_INCOME_MAIN"("CUSTOMER_NAME");
CREATE INDEX "IDX_INC_INCOME_MAIN_STATUS" ON "ADMIN"."INC_INCOME_MAIN"("COLLECTION_STATUS");

CREATE INDEX "IDX_INC_INCOME_HIST_INCOME_ID" ON "ADMIN"."INC_INCOME_HIST"("INCOME_ID");
CREATE INDEX "IDX_INC_INCOME_HIST_MOTIFY_TIME" ON "ADMIN"."INC_INCOME_HIST"("MOTIFY_TIME");

-- ============================================================================
-- 4. 欄位說明
-- ============================================================================
/*
INC_INCOME_MAIN (收入記帳主表)
├─ SID: 系統唯一識別碼（主鍵）
├─ INCOME_ID: 收入紀錄編號（唯一值）
├─ BILL_DATE: 日期
├─ INVOICE_NO: 憑據（發票/收據號碼）
├─ CUSTOMER_NAME: 客戶名稱
├─ PROJECT: 工項
├─ PERSONNEL: 施作人員
├─ LOCATION: 地點
├─ QUOTE_AMOUNT: 報價金額
├─ ACTUAL_AMOUNT: 實做金額
├─ UNCOLLECTED_AMOUNT: 未收金額
├─ COLLECTION_METHOD: 收款方式（現金/支票/轉帳等）
├─ COLLECTION_STATUS: 收款狀態（Y/N）
├─ COST_AMOUNT: 成本金額
├─ ESTIMATED_PROFIT: 預估毛利
├─ REMARK: 備註
├─ CREATE_USER: 建立使用者
├─ CREATE_TIME: 建立時間
├─ MOTIFER: 修改者
└─ MOTIFY_TIME: 修改時間

INC_INCOME_HIST (收入記帳歷史表)
└─ 同上結構，用於記錄所有歷史版本
*/
